---
roles:
  - blobstore:    ec2-10-2-3-4.compute-1.amazonaws.com
  - nats:         ec2-10-2-3-4.compute-1.amazonaws.com
  - postgresql:   ec2-10-2-3-4.compute-1.amazonaws.com
  - redis:        ec2-10-2-3-4.compute-1.amazonaws.com
  - director:     ec2-10-2-3-4.compute-1.amazonaws.com
  - aws_registry: ec2-10-2-3-4.compute-1.amazonaws.com
user: ubuntu
paths:
  repo_cache: /var/vcap/deploy/repos
  cookbooks: /var/vcap/deploy/cookbooks
  chef: /var/vcap/deploy/chef
chef_node:
  director:
    runner: root
    aws:
      access_key_id:     ACCESS_KEY_ID
      secret_access_key: SECRET_ACCESS_KEY
      default_key_name: fog_default
      default_security_groups: ["default"]
      ec2_endpoint: ec2.us-west-2.amazonaws.com
      max_retries: 2
  aws_registry:
    endpoint: http://admin:admin@ec2-10-2-3-4.compute-1.amazonaws.com:25777
    http:
      user: admin
      passwrd: admin