---
name: wordpress
director_uuid: 74cee69e-2cd8-4c99-96c8-f332e4967021

release:
  name: wordpress
  version: 3

compilation:
  workers: 4
  network: default
  cloud_properties:
    ram: 2048
    disk: 8096
    cpu: 2

# this section describes how updates are handled
update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4
  max_errors: 1

networks:
  - name: default
    type: dynamic
    ip: 23.23.10.10
    cloud_properties:
      security_groups:
      - default
  - name: nginx
    type: vip
    ip: 23.23.10.10
    cloud_properties:
      security_groups:
      - default
  - name: wordpress
    type: vip
    ip: 23.23.20.10
    cloud_properties:
      security_groups:
      - default
  - name: mysql
    type: vip
    ip: 23.23.30.10
    cloud_properties:
      security_groups:
      - default

resource_pools:
  - name: common
    network: default
    size: 3
    stemcell:
      name: bosh-stemcell
      version: 0.5.1
    cloud_properties:
      disk: 8192
      instance_type: m1.small
      availability_zone:
      key_name: 

jobs:
  - name: nginx
    template: nginx
    instances: 1
    resource_pool: common
    networks:
    - name: default
      static_ips:
        - 23.23.10.10

  - name: wordpress
    template: wordpress
    instances: 1
    resource_pool: infrastructure
    networks:
    - name: default
      static_ips:
      - 23.23.20.10

  - name: mysql
    template: mysql
    instances: 1
    resource_pool: infrastructure
    persistent_disk: 16384
    networks:
    - name: default
      static_ips:
      - 23.23.30.10

properties:

  nginx:
    workers: 1

  wordpress:
    admin: foo@bar.com
    port: 8008
    servers:
      - 23.23.20.10
    servername: ec2-23-23-10-10.compute-1.amazonaws.com
    db:
      name: wp
      user: wordpress
      pass: w0rdpr3ss
    auth_key: random key
    secure_auth_key: random key
    logged_in_key: random key
    nonce_key: random key
    auth_salt: random key
    secure_auth_salt: random key
    logged_in_salt: random key
    nonce_salt: random key

  mysql:
    address: 23.23.30.10
    port: 3306
    password: rootpass

cloud:
  plugin: aws
  properties:
    aws:
      access_key_id:     ACCESS_KEY
      secret_access_key: SECRET_ACCESS_KEY
      default_key_name: fog_default
      default_security_groups: ["default"]
      ec2_endpoint: ec2.us-east-1.amazonaws.com
      max_retries: 2
    registry:
      endpoint: http://admin:admin@BOSH_AWS_REGISTRY_DNS_NAME:25777
      user: admin
      password: admin
